### ISSUE TITLE
Script não ignora a pasta .git ao deletar diretórios vazios

### ISSUE THREAD

**Issue by ParagonVirtuoso** [sailleribeiro/script-delete-empty-folders#1]
Olá!

Estou utilizando o script disponibilizado e notei que ele remove a pasta .git se ela estiver vazia, o que pode comprometer o funcionamento do repositório Git. Acredito que o comportamento ideal seria o script ignorar pastas específicas, como .git, mesmo que estejam vazias.

Problema:

O script atual lista e pergunta sobre a exclusão de qualquer pasta vazia, incluindo pastas essenciais como .git. Isso pode causar problemas de controle de versão no repositório.
Sugestão:

Adicionar uma verificação para ignorar diretórios como .git ou qualquer outro que seja crítico para o funcionamento do repositório.

**Comment by sailleribeiro** [comment]
Olá Denys, fico feliz com seu Feedback. 

Já foi disponibilizado uma atualização que contempla o problema que você reportou, pastas essenciais e cruciais foram ignoradas para garantir o funcionamento correto da aplicação.
